# See https://pub.dev/packages/mono_repo for details

sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
    - group:
      - format
      - analyze: '| sed "s/^   info/warning/g"'
      sdk: stable
  - unit_test:
    - test: --test-randomize-ordering-seed=random

# vim: set et ts=2 sw=2:
