name: dwn_sdk
description: A Dart implementation of Distributed Web Node (DWN)
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart
repository: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
