name: dwn_sdk
description: A Dart implementation of Decentralized Web Node (DWN)
version: 0.1.0-dev.2
homepage: https://github.com/heacare/habitat-sdk-dart
repository: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.4
  jose2: ^0.3.4
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.16.0
