name: dwn_sdk
description: A Dart implementation of Distributed Web Node (DWN)
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart
repository: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  #jose: ^0.3.2
  jose:
    git:
      url: https://github.com/heacare/jose.git
      ref: unprotected-optional

dev_dependencies:
  test: ^1.16.0
