name: dwn_sdk
description: A Dart implementation of Distributed Web Node (DWN)
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart
repository: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.4
  #jose: ^0.3.2
  jose:
    git:
      url: https://github.com/heacare/jose.git
      ref: unprotected-optional
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.16.0
dependencies: {build_runner: ^2.2.0, http: ^0.13.4, json_serializable: ^6.3.1}
