name: habitat_sdk
description: A Dart implementation of Habitat, an open, composable data network built on top of DWN
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  webcrypto: ^0.5.2

dev_dependencies:
  test: ^1.16.0
