name: habitat_sdk
description: A Dart implementation of Habitat, an open, composable data network built on top of DWN
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart
repository: https://github.com/heacare/habitat-sdk-dart

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  webcrypto:
    git:
      url: https://github.com/heacare/webcrypto.dart.git
      ref: fix-package-resolution

dev_dependencies:
  test: ^1.16.0
