name: habitat_sdk
description: A Dart implementation of Habitat, an open, composable data network built on top of DWN
version: 0.1.0
homepage: https://github.com/heacare/habitat-sdk-dart/tree/main/habitat_sdk
repository: https://github.com/heacare/habitat-sdk-dart
issue_tracker: https://github.com/heacare/habitat-sdk-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dwn_sdk: 0.1.0-dev.2

dev_dependencies:
  test: ^1.16.0
