# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_002:
    name: "analyze_and_format; Dart stable; PKG: dwn_sdk; `dart format --output=none --set-exit-if-changed .`, `dart analyze | sed \"s/^   info/warning/g\"`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:dwn_sdk;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:dwn_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: dwn_sdk_pub_upgrade
        name: dwn_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: dwn_sdk
        run: dart pub upgrade
      - name: "dwn_sdk; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.dwn_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: dwn_sdk
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "dwn_sdk; dart analyze | sed \"s/^   info/warning/g\""
        if: "always() && steps.dwn_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: dwn_sdk
        run: "dart analyze | sed \"s/^   info/warning/g\""
  job_003:
    name: "analyze_and_format; Dart stable; PKG: habitat_sdk; `dart format --output=none --set-exit-if-changed .`, `dart analyze | sed \"s/^   info/warning/g\"`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:habitat_sdk;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: habitat_sdk_pub_upgrade
        name: habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: habitat_sdk
        run: dart pub upgrade
      - name: "habitat_sdk; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: habitat_sdk
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "habitat_sdk; dart analyze | sed \"s/^   info/warning/g\""
        if: "always() && steps.habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: habitat_sdk
        run: "dart analyze | sed \"s/^   info/warning/g\""
  job_004:
    name: "unit_test; Dart dev; PKG: dwn_sdk; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:dwn_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:dwn_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: dwn_sdk_pub_upgrade
        name: dwn_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: dwn_sdk
        run: dart pub upgrade
      - name: "dwn_sdk; dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.dwn_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: dwn_sdk
        run: "dart test --test-randomize-ordering-seed=random"
    needs:
      - job_002
      - job_003
  job_005:
    name: "unit_test; Dart dev; PKG: habitat_sdk; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:habitat_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: habitat_sdk_pub_upgrade
        name: habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: habitat_sdk
        run: dart pub upgrade
      - name: "habitat_sdk; dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: habitat_sdk
        run: "dart test --test-randomize-ordering-seed=random"
    needs:
      - job_002
      - job_003
  job_006:
    name: "unit_test; Dart stable; PKG: dwn_sdk; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:dwn_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:dwn_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: dwn_sdk_pub_upgrade
        name: dwn_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: dwn_sdk
        run: dart pub upgrade
      - name: "dwn_sdk; dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.dwn_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: dwn_sdk
        run: "dart test --test-randomize-ordering-seed=random"
    needs:
      - job_002
      - job_003
  job_007:
    name: "unit_test; Dart stable; PKG: habitat_sdk; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:habitat_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: heacare/setup-dart@add-matcher
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: habitat_sdk_pub_upgrade
        name: habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: habitat_sdk
        run: dart pub upgrade
      - name: "habitat_sdk; dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: habitat_sdk
        run: "dart test --test-randomize-ordering-seed=random"
    needs:
      - job_002
      - job_003
