# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.3.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze; Dart stable; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_habitat_sdk_pub_upgrade
        name: packages/habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart pub upgrade
      - name: packages/habitat_sdk; dart analyze
        if: "always() && steps.packages_habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart analyze
  job_003:
    name: "format; Dart stable; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_habitat_sdk_pub_upgrade
        name: packages/habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart pub upgrade
      - name: "packages/habitat_sdk; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: "dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
      - job_002
  job_004:
    name: "test; Dart dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/habitat_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_habitat_sdk_pub_upgrade
        name: packages/habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart pub upgrade
      - name: packages/habitat_sdk; dart test
        if: "always() && steps.packages_habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "test; Dart stable; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/habitat_sdk
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_habitat_sdk_pub_upgrade
        name: packages/habitat_sdk; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart pub upgrade
      - name: packages/habitat_sdk; dart test
        if: "always() && steps.packages_habitat_sdk_pub_upgrade.conclusion == 'success'"
        working-directory: packages/habitat_sdk
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
